# Generated by Django 3.2.7 on 2021-09-28 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itelapp', '0002_auto_20210928_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True, 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
