# Generated by Django 3.2.7 on 2021-09-30 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itelapp', '0003_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(default='cat.jpg', upload_to='product')),
                ('min_quant', models.IntegerField()),
                ('max_quant', models.IntegerField()),
                ('latest', models.BooleanField()),
                ('Best_seller', models.BooleanField()),
                ('avaliable', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itelapp.category')),
            ],
        ),
    ]
