# Generated by Django 3.2.7 on 2021-09-30 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itelapp', '0004_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Best_seller',
            new_name='best_seller',
        ),
    ]
